//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.03.03 at 09:57:56 PM GMT 
//


package au.net.ohalloran.yahap.services.model.ws.jaxws;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the au.net.ohalloran.yahap.services.model.ws.jaxws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AddDevice_QNAME = new QName("http://ws.model.services.yahap.ohalloran.net.au/", "addDevice");
    private final static QName _AddDeviceResponse_QNAME = new QName("http://ws.model.services.yahap.ohalloran.net.au/", "addDeviceResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: au.net.ohalloran.yahap.services.model.ws.jaxws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddDevice }
     * 
     */
    public AddDevice createAddDevice() {
        return new AddDevice();
    }

    /**
     * Create an instance of {@link AddDeviceResponse }
     * 
     */
    public AddDeviceResponse createAddDeviceResponse() {
        return new AddDeviceResponse();
    }

    /**
     * Create an instance of {@link Device }
     * 
     */
    public Device createDevice() {
        return new Device();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddDevice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.model.services.yahap.ohalloran.net.au/", name = "addDevice")
    public JAXBElement<AddDevice> createAddDevice(AddDevice value) {
        return new JAXBElement<AddDevice>(_AddDevice_QNAME, AddDevice.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddDeviceResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.model.services.yahap.ohalloran.net.au/", name = "addDeviceResponse")
    public JAXBElement<AddDeviceResponse> createAddDeviceResponse(AddDeviceResponse value) {
        return new JAXBElement<AddDeviceResponse>(_AddDeviceResponse_QNAME, AddDeviceResponse.class, null, value);
    }

}
