//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.03.03 at 09:57:56 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ws.model.services.yahap.ohalloran.net.au/")
package au.net.ohalloran.yahap.services.model.ws.jaxws;
